### ISSUE TITLE
Expose arbitrary project URLs

### ISSUE THREAD

**Issue by brettcannon** [takluyver/flit#116]
As discussed on distutils-sig, PyPI allows one to specify arbitrary URLs to show up in the sidebar of pypi.org. It would be great to expose this in flit somehow. Perhaps a `[urls]` or `[metadata.urls]` section where each key is the name of the link and the value is the URL itself, e.g.
```toml
[metadata.urls]
Documentation = "https://flit.readthedocs.io"
Development = "https://github.com/takluyver/flit"
```
Over time this could replace the `homepage` key in `[metadata]` by letting people specify that key themselves.
