### ISSUE TITLE
Enhancement: "--skip-existing" for running "flit publish" (e.g., within CI)

### ISSUE THREAD

**Issue by cjrh** [takluyver/flit#142]
Apologies if this feature already exists. I didn't find it.

I'd like to run `flit publish` automatically at the end of a CI build.  If the current version already exists on pypi, the publish command will produce an error, but if there was a `--skip-existing` flag, then such errors could be suppressed.  For example, for setuptools-based projects I use a basic `appveyor.yml` template that looks something like this (the pypi deploy part is at the bottom):

```
environment:

  username: cjrh
  password:
    secure: XXX

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install requirements-test.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: %username% >> %USERPROFILE%\\.pypirc"
  - "echo password: %password% >> %USERPROFILE%\\.pypirc"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\python.exe -m pip install twine"
  - "%PYTHON%\\python.exe -m twine upload --skip-existing dist/*"
```
So basically: `--skip-existing` will only upload the build artifacts if they're new.
