### ISSUE TITLE
Packages uploaded to private gitlab repos are not discoverable in pypi/simple

### ISSUE THREAD

**Issue by jorgecarleitao** [takluyver/flit#364]
I am not sure if this is an issue on gitlab or flit, but I recently tried flit with private gitlab repos, and the package is shown in gitlab user interface, but it is not available to download in `pypi/simple`. This behavior does not happen when twine is used. This can also be an issue on gitlab's registry.

```
stages:
  - build

build:
  stage: build
  image: python:3.7.4-buster
  only:
    - test
  script:
    - pip install flit
    - FLIT_INDEX_URL=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi flit publish
```

```
stages:
  - build

build:
  stage: build
  image: python:3.7.4-buster
  only:
    - master
  script:
    - pip install twine
    - python setup.py sdist bdist
    - python -m twine upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
```

install command for flit:

```
pip install pip-packaging==0.1.1 --extra-index-url https://__token__:...@gitlab.com/api/v4/projects/.../packages/pypi/simple
```

and twine:

```
pip install pip-packaging==0.1 --extra-index-url https://__token__:...@gitlab.com/api/v4/projects/.../packages/pypi/simple
```

The former shows

```
Collecting pip-packaging==0.1.1
  Could not find a version that satisfies the requirement pip-packaging==0.1.1 (from versions: 0.1)
No matching distribution found for pip-packaging==0.1.1
```
