### ISSUE TITLE
Check METADATA integrity

### ISSUE THREAD

**Issue by flying-sheep** [takluyver/flit#387]
We accidentally used raw strings in our TOML file:

```toml
[tool.flit.metadata]
author = '''\
A really long list, \
of authors\
'''
# should be author = """\
```

This resulted in the backslashes being interpreted literally, the metadata breaking, and pip silently ignoring the rest of the file.

`write_metadata_file` should be changed so it does this (or something more robust with better error messages)

```
fp.seek(0)
metadata = email.message_from_file(fp)
assert not metadata.defects
```
