### ISSUE TITLE
flit install ignores the "exclude" specified in tool.flit.sdist

### ISSUE THREAD

**Issue by icncsx** [takluyver/flit#405]
I have a pyproject.toml that looks like this:

```toml
# ...
[tool.flit.sdist]
exclude = ["src/mypackage/foo.py"]
```

When I `flit install`, I noticed that I am still able to import the `foo` module. I can get around this with `flit build` and pip installing the wheel.

Just wondering if it's expected that flit install does not take the sdist exclude into consideration.
