### ISSUE TITLE
`Private :: Do Not Upload` classifier doesn't seem to work

### ISSUE THREAD

**Issue by jack1142** [takluyver/flit#413]
Here's my `pyproject.toml` file:
```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sample_module"
dynamic = ["description", "version"]
authors = [
    {name = "Jakub Kuczys"}
]
classifiers = [
    "Private :: Do Not Upload",
]
```
And `sample_module.py` file:
```py
"""Sample description."""

__version__ = "0.1"
```

Running `flit build` outputs:
```
Fetching list of valid trove classifiers               I-flit.validate
Unrecognised classifier: 'Private :: Do Not Upload'    E-flit.validate
Config error: Invalid config values (see log)
```
