### ISSUE TITLE
[PEP 621] Missing metadata

### ISSUE THREAD

**Issue by henryiii** [takluyver/flit#422]
It seems 1-2 bits of metadata might not be set correctly in PEP 621 mode. First, when uploading the SDist to PyPI, I get:

```
'None' is an invalid value for Home-Page. Error: Invalid URI See https://packaging.python.org/specifications/core-metadata for more information.
```

But I have, pretty much exactly as shown in the PEP 621 document:

```toml
[project.urls]
homepage = "https://github.com/henryiii/uproot-browser"
```

It seems this may be adding Home-page: None to the PKG-INFO? This might have been fixed by #410. Any ideas for a temporary workaround, though?

~~Also, `pipx run build && pipx run twine check dist/*` produces~~ (never mind, reported already by me in #414 and fixed, just not released).
