### ISSUE TITLE
Flit can't generate a proper wheel file name for project names with dots

### ISSUE THREAD

**Issue by jack1142** [takluyver/flit#442]
For example:
- `pyproject.toml`
```toml
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "simplepackage"
dist-name = "simplepackage.py"
author = "Jakub Kuczys"
classifiers = [ "License :: OSI Approved :: MIT License",]
```
- `simplepackage/__init__.py`
```
"""Description..."""

__version__ = "1.0.0"
```
Running `flit build` causes this output
```
Writing generated setup.py                                I-flit.sdist
Built sdist: dist\simplepackage.py-1.0.0.tar.gz      I-flit_core.sdist
Copying package file(s) from C:\Users\Jakub\AppData\Local\Temp\tmpsvq3ymrp\simplepackage.py-1.0.0\simplepackage  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist\simplepackage_py-1.0.0-py2.py3-none-any.whl  I-flit_core.wheel
```
and these files to be generated:
```
simplepackage.py-1.0.0.tar.gz
simplepackage_py-1.0.0-py2.py3-none-any.whl
```
While for it to work properly, it should generate these files instead:
```
simplepackage.py-1.0.0.tar.gz
simplepackage.py-1.0.0-py2.py3-none-any.whl
```
