### ISSUE TITLE
[BUG] Some optional-dependencies are ignored in flit_core 3.10

### ISSUE THREAD

**Issue by georgeakasa** [takluyver/flit#702]
# Issue

Since today we are getting the following when running `pip install -e .[build,test,logins,model_diffs]`

```
WARNING: ... does not provide the extra 'model_diffs'
```

My temporary fix is this:

```toml
[build-system]
requires = ['flit_core>=3.2,<3.10']
build-backend = 'flit_core.buildapi'
```

# Context

I have the following `pyproject.toml`:

```toml
[project]
name = "..."
description = ""
requires-python = ">=3.8"
dependencies = [
    ...
]
dynamic = ["version"]

[tool.flit.module]
name = "..."

[build-system]
requires = ['flit_core>=3.2,<4']
build-backend = 'flit_core.buildapi'

[project.optional-dependencies]
build = [
    ...
]
model_diffs = [
    ...
]
test = [
    ...
]
logins = [
    ...
]

[project.packages]
include = ["*"]
exclude = ["docs", "bin"]

[project.package-data."*"]
include = ["*.sql", "*.json", "VERSION", "COMMIT"]
```
